import { db } from "@workspace/db";
import {
  jarvisApprovalsTable,
  jarvisCommandsTable,
  jarvisDelegationsTable,
  jarvisWorkflowStepsTable,
  jarvisEscalationsTable,
} from "@workspace/db";
import { and, asc, eq, inArray } from "drizzle-orm";
import { agentBus } from "../agentBus.js";
import { recordGovernanceOutcome } from "../governance/index.js";

/**
 * Governance resume pass — the FRONT of the pump. It consumes auto-generated
 * approvals that a human has resolved and either releases the parked subject back
 * into its actionable queue (approved) or moves it to a terminal blocked state
 * (rejected). Idempotent: it only acts on subjects still in `pending_approval`,
 * so a resolved approval is reconciled exactly once. Advisory-safe — never
 * deletes, only NARROWS or releases an already-held subject.
 */

const MAX_RESUME_PER_TICK = 25;

export async function pumpGovernanceResume(): Promise<number> {
  const resolved = await db
    .select()
    .from(jarvisApprovalsTable)
    .where(
      and(
        eq(jarvisApprovalsTable.autoGenerated, true),
        inArray(jarvisApprovalsTable.status, ["approved", "rejected"]),
      ),
    )
    .orderBy(asc(jarvisApprovalsTable.createdAt), asc(jarvisApprovalsTable.id))
    .limit(MAX_RESUME_PER_TICK);

  let acted = 0;
  for (const ap of resolved) {
    if (!ap.subjectType || !ap.subjectId) continue;
    const approved = ap.status === "approved";
    const handled = await resumeSubject(
      ap.subjectType,
      ap.subjectId,
      approved,
      ap.decisionReason ?? null,
    );
    if (handled) acted += 1;
  }
  return acted;
}

async function resumeSubject(
  subjectType: string,
  subjectId: string,
  approved: boolean,
  reason: string | null,
): Promise<boolean> {
  const now = new Date();
  const blockedReason = reason ?? "blocked by governance approval";

  switch (subjectType) {
    case "command": {
      const [row] = await db
        .select()
        .from(jarvisCommandsTable)
        .where(eq(jarvisCommandsTable.id, subjectId))
        .limit(1);
      if (!row || row.governanceState !== "pending_approval") return false;
      await db
        .update(jarvisCommandsTable)
        .set(
          approved
            ? { governanceState: "approved", status: "received", updatedAt: now }
            : {
                governanceState: "blocked",
                status: "rejected",
                error: blockedReason,
                updatedAt: now,
              },
        )
        .where(eq(jarvisCommandsTable.id, subjectId));
      await recordGovernanceOutcome({
        agentId: null,
        agentType: row.routedAgentType ?? null,
        approved,
        denied: !approved,
      });
      emitResumed("command", subjectId, approved, row.routedAgentType ?? null);
      return true;
    }
    case "delegation": {
      const [row] = await db
        .select()
        .from(jarvisDelegationsTable)
        .where(eq(jarvisDelegationsTable.id, subjectId))
        .limit(1);
      if (!row || row.governanceState !== "pending_approval") return false;
      await db
        .update(jarvisDelegationsTable)
        .set(
          approved
            ? { governanceState: "approved", status: "assigned", updatedAt: now }
            : {
                governanceState: "blocked",
                status: "declined",
                error: blockedReason,
                updatedAt: now,
              },
        )
        .where(eq(jarvisDelegationsTable.id, subjectId));
      await recordGovernanceOutcome({
        agentId: row.toAgentId ?? null,
        agentType: null,
        approved,
        denied: !approved,
      });
      emitResumed("delegation", subjectId, approved, null);
      return true;
    }
    case "workflow_step": {
      const [row] = await db
        .select()
        .from(jarvisWorkflowStepsTable)
        .where(eq(jarvisWorkflowStepsTable.id, subjectId))
        .limit(1);
      if (!row || row.governanceState !== "pending_approval") return false;
      await db
        .update(jarvisWorkflowStepsTable)
        .set(
          approved
            ? { governanceState: "approved", status: "pending" }
            : {
                governanceState: "blocked",
                status: "failed",
                error: blockedReason,
                finishedAt: now,
              },
        )
        .where(eq(jarvisWorkflowStepsTable.id, subjectId));
      await recordGovernanceOutcome({
        agentId: row.agentId ?? null,
        agentType: row.agentType ?? null,
        approved,
        denied: !approved,
      });
      emitResumed("workflow_step", subjectId, approved, row.agentType ?? null);
      return true;
    }
    case "escalation": {
      const [row] = await db
        .select()
        .from(jarvisEscalationsTable)
        .where(eq(jarvisEscalationsTable.id, subjectId))
        .limit(1);
      if (!row || row.governanceState !== "pending_approval") return false;
      await db
        .update(jarvisEscalationsTable)
        .set(
          approved
            ? { governanceState: "approved", nextEscalationAt: now, updatedAt: now }
            : { governanceState: "blocked", updatedAt: now },
        )
        .where(eq(jarvisEscalationsTable.id, subjectId));
      await recordGovernanceOutcome({
        agentId: row.assigneeAgentId ?? null,
        agentType: null,
        approved,
        denied: !approved,
      });
      emitResumed("escalation", subjectId, approved, null);
      return true;
    }
    default:
      return false;
  }
}

function emitResumed(
  subjectType: string,
  subjectId: string,
  approved: boolean,
  agentType: string | null,
): void {
  agentBus.emitEvent({
    type: "governance_resumed",
    severity: approved ? "success" : "warn",
    agentType,
    message: `Governance ${approved ? "approved" : "blocked"} ${subjectType} resumed`,
    details: { subjectId, approved },
  });
}
