import { db } from "@workspace/db";
import {
  jarvisPoliciesTable,
  jarvisPolicyEvaluationsTable,
  jarvisApprovalsTable,
  jarvisCommandsTable,
  jarvisDelegationsTable,
  jarvisWorkflowStepsTable,
  jarvisEscalationsTable,
} from "@workspace/db";
import { asc, eq } from "drizzle-orm";
import { evaluatePolicy } from "./policyEngine.js";
import { getTrustScore } from "./trust.js";
import { checkBudget } from "./budgets.js";
import { recomputeAllTrust } from "./trust.js";
import { resetExpiredBudgets } from "./budgets.js";
import type {
  GovernanceDecision,
  GovernanceResult,
  GovernedSubject,
  GovernedSubjectType,
  PolicyConditions,
} from "./types.js";

export * from "./types.js";
export {
  evaluatePolicy,
  scopeMatches,
  scopeSpecificity,
} from "./policyEngine.js";
export {
  computeTrustScore,
  getTrustScore,
  recordRunOutcome,
  recordGovernanceOutcome,
  recomputeAllTrust,
} from "./trust.js";
export {
  isWindowExpired,
  budgetMatches,
  checkBudget,
  consumeBudget,
  resetExpiredBudgets,
} from "./budgets.js";

/**
 * Governance entrypoint. Combines the pure policy verdict with live trust +
 * budget signals into a single deterministic decision. Escalation is MONOTONIC —
 * trust/budget can only strengthen the verdict (allow → require_approval → deny),
 * never relax it. Read-only: callers record the evaluation + consume budget.
 */
export async function evaluateGovernance(
  subject: GovernedSubject,
): Promise<GovernanceResult> {
  const policies = await db
    .select()
    .from(jarvisPoliciesTable)
    .orderBy(asc(jarvisPoliciesTable.createdAt), asc(jarvisPoliciesTable.id));
  const base = evaluatePolicy(subject, policies);

  const trustScore = await getTrustScore(
    subject.agentId ?? null,
    subject.agentType ?? null,
  );
  const matchedBudget = await checkBudget(subject);

  let decision: GovernanceDecision = base.decision;
  let reason = base.reason;

  const conditions = (base.policy?.conditions ?? {}) as PolicyConditions;
  if (
    decision === "allow" &&
    typeof conditions.minTrustScore === "number" &&
    trustScore !== null &&
    trustScore < conditions.minTrustScore
  ) {
    decision = "require_approval";
    reason = `trust ${trustScore} < required ${conditions.minTrustScore} — approval required`;
  }

  // Budget exhaustion is the strongest constraint and always denies.
  if (matchedBudget?.exceeded) {
    decision = "deny";
    reason = `budget "${matchedBudget.name}" exhausted (${matchedBudget.consumed}/${matchedBudget.limitCount})`;
  }

  return {
    decision,
    policyId: base.policy?.id ?? null,
    policyName: base.policy?.name ?? null,
    reason,
    requireApprovalRole: base.policy?.requireApprovalRole ?? "admin",
    trustScore,
    matchedBudget,
  };
}

/** Persist an immutable governance decision row; returns its id. */
export async function recordEvaluation(
  subject: GovernedSubject,
  result: GovernanceResult,
  approvalId: string | null = null,
): Promise<string> {
  const [row] = await db
    .insert(jarvisPolicyEvaluationsTable)
    .values({
      policyId: result.policyId,
      policyName: result.policyName,
      subjectType: subject.subjectType,
      subjectId: subject.subjectId,
      agentType: subject.agentType ?? null,
      action: subject.action ?? subject.verb ?? null,
      decision: result.decision,
      reason: result.reason,
      approvalId,
      trustScoreAtEval: result.trustScore,
      budgetSnapshot: result.matchedBudget
        ? { ...result.matchedBudget }
        : null,
    })
    .returning({ id: jarvisPolicyEvaluationsTable.id });
  return row!.id;
}

/** Create an auto-generated approval that pauses a subject; returns its id. */
export async function createGovernanceApproval(
  subject: GovernedSubject,
  result: GovernanceResult,
  title: string,
): Promise<string> {
  const [row] = await db
    .insert(jarvisApprovalsTable)
    .values({
      title,
      description: result.reason,
      status: "pending",
      requestedBy: "governance",
      policyId: result.policyId,
      subjectType: subject.subjectType,
      subjectId: subject.subjectId,
      autoGenerated: true,
      decisionReason: result.reason,
    })
    .returning({ id: jarvisApprovalsTable.id });
  return row!.id;
}

export interface SubjectGovernanceFields {
  governanceState?: string;
  policyEvaluationId?: string | null;
  approvalId?: string | null;
}

/** Update the governance columns on whichever subject table owns the subject. */
export async function markSubjectGovernance(
  subjectType: GovernedSubjectType,
  subjectId: string,
  fields: SubjectGovernanceFields,
): Promise<void> {
  const now = new Date();
  switch (subjectType) {
    case "command":
      await db
        .update(jarvisCommandsTable)
        .set({ ...fields, updatedAt: now })
        .where(eq(jarvisCommandsTable.id, subjectId));
      return;
    case "delegation":
      await db
        .update(jarvisDelegationsTable)
        .set({ ...fields, updatedAt: now })
        .where(eq(jarvisDelegationsTable.id, subjectId));
      return;
    case "workflow_step":
      // jarvis_workflow_steps has no updatedAt column.
      await db
        .update(jarvisWorkflowStepsTable)
        .set({ ...fields })
        .where(eq(jarvisWorkflowStepsTable.id, subjectId));
      return;
    case "escalation":
      await db
        .update(jarvisEscalationsTable)
        .set({ ...fields, updatedAt: now })
        .where(eq(jarvisEscalationsTable.id, subjectId));
      return;
  }
}

/** Tail maintenance pass: recompute trust scores then reset expired budgets. */
export async function runGovernanceMaintain(): Promise<{
  trustRows: number;
  budgetsReset: number;
}> {
  const trustRows = await recomputeAllTrust();
  const budgetsReset = await resetExpiredBudgets();
  return { trustRows, budgetsReset };
}
