import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import downloadRouter from "./download.js";
import signalsRouter from "./signals.js";
import tradesRouter from "./trades.js";
import portfolioRouter from "./portfolio.js";
import settingsRouter from "./settings.js";
import logsRouter from "./logs.js";
import backtestRouter from "./backtest.js";
import candlesRouter from "./candles.js";
import marketDataRouter from "./marketData.js";
import analysisRouter from "./analysis.js";
import aiDecisionRouter from "./aiDecision.js";
import riskManagementRouter from "./riskManagement.js";
import simulationRouter from "./simulation.js";
import optimizerRouter from "./optimizer.js";
import scannerRouter from "./scanner.js";
import correlationRouter from "./correlation.js";
import journalRouter from "./journal.js";
import executionStateRouter from "./executionState.js";
import validationRouter from "./validation.js";
import sentimentRouter from "./sentiment.js";
import exchangeRouter from "./exchange.js";
import exchangeCatalogRouter from "./exchangeCatalog.js";
import engineRouter from "./engine.js";
import systemRouter from "./system.js";
import feesRouter from "./fees.js";
import mobileRouter from "./mobile.js";
import adaptersRouter from "./adapters.js";
import authRouter from "./auth.js";
import userSettingsRouter from "./userSettings.js";
import aiTradingRouter from "./aiTrading.js";
import userNotificationsRouter from "./userNotifications.js";
import alpacaPaperRouter from "./alpacaPaper.js";
import userExchangesRouter from "./userExchanges.js";
import runtimeStateRouter from "./runtimeState.js";
import userLiveOrderRouter from "./userLiveOrder.js";
import userTradeLimitRouter from "./userTradeLimit.js";
import alpacaBrokerRouter from "./alpacaBroker.js";
import billingRouter from "./billing.js";
import adminAnalyticsRouter from "./adminAnalytics.js";
import platformOverviewRouter from "./platformOverview.js";
import operatorTelemetryRouter from "./operatorTelemetry.js";
import adminTopTelemetryRouter from "./adminTopTelemetry.js";
import adminExecutionFunnelRouter from "./adminExecutionFunnel.js";
import adminBackfillStatusRouter from "./adminBackfillStatus.js";
import adminTradesRouter from "./adminTrades.js";
import adminFeesRouter from "./adminFees.js";
import adminUserTelemetryRouter from "./adminUserTelemetry.js";
import adminUserActionsRouter from "./adminUserActions.js";
import adminUserProfileRouter from "./adminUserProfile.js";
import adminSessionsRouter from "./adminSessions.js";
import adminExchangeConnectionsRouter from "./adminExchangeConnections.js";
import adminAiUsageRouter from "./adminAiUsage.js";
import adminUserExchangeVisibilityRouter from "./adminUserExchangeVisibility.js";
import userConsentRouter from "./userConsent.js";
import pushTokensRouter from "./pushTokens.js";
import internalNotifyRouter from "./internalNotify.js";
import executionDebugRouter from "./executionDebug.js";
import userRiskSettingsRouter from "./userRiskSettings.js";
import adminRiskEventsRouter from "./adminRiskEvents.js";
import aiDisclaimerRouter from "./aiDisclaimer.js";
import userAiLiquidityRouter from "./userAiLiquidity.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(downloadRouter);
router.use(authRouter);
router.use(userSettingsRouter);
router.use(userRiskSettingsRouter);
router.use(adminRiskEventsRouter);
router.use(aiDisclaimerRouter);
router.use(aiTradingRouter);
router.use(userAiLiquidityRouter);
router.use(userNotificationsRouter);
router.use(userExchangesRouter);
router.use(runtimeStateRouter);
router.use(userLiveOrderRouter);
router.use(userTradeLimitRouter);
router.use(alpacaBrokerRouter);
router.use(billingRouter);
router.use(adminAnalyticsRouter);
router.use(platformOverviewRouter);
router.use(operatorTelemetryRouter);
router.use(adminTopTelemetryRouter);
router.use(adminExecutionFunnelRouter);
router.use(adminBackfillStatusRouter);
router.use(adminTradesRouter);
router.use(adminFeesRouter);
router.use(adminUserTelemetryRouter);
router.use(adminUserActionsRouter);
router.use(adminUserProfileRouter);
router.use(adminSessionsRouter);
router.use(adminExchangeConnectionsRouter);
router.use(adminAiUsageRouter);
router.use(adminUserExchangeVisibilityRouter);
router.use(userConsentRouter);
router.use(pushTokensRouter);
router.use(internalNotifyRouter);
router.use(executionDebugRouter);
router.use(signalsRouter);
router.use(tradesRouter);
router.use(portfolioRouter);
router.use(settingsRouter);
router.use(logsRouter);
router.use(backtestRouter);
router.use(candlesRouter);
router.use(marketDataRouter);
router.use(analysisRouter);
router.use(aiDecisionRouter);
router.use(riskManagementRouter);
router.use(simulationRouter);
router.use(optimizerRouter);
router.use(scannerRouter);
router.use(correlationRouter);
router.use(journalRouter);
router.use(validationRouter);
router.use(sentimentRouter);
router.use(exchangeRouter);
router.use(exchangeCatalogRouter);
router.use(engineRouter);
router.use(executionStateRouter);
router.use(systemRouter);
router.use(feesRouter);
router.use(mobileRouter);
router.use(adaptersRouter);
router.use(alpacaPaperRouter);

export default router;
