import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import downloadRouter from "./download.js";
import signalsRouter from "./signals.js";
import tradesRouter from "./trades.js";
import portfolioRouter from "./portfolio.js";
import settingsRouter from "./settings.js";
import logsRouter from "./logs.js";
import backtestRouter from "./backtest.js";
import candlesRouter from "./candles.js";
import marketDataRouter from "./marketData.js";
import analysisRouter from "./analysis.js";
import aiDecisionRouter from "./aiDecision.js";
import riskManagementRouter from "./riskManagement.js";
import simulationRouter from "./simulation.js";
import optimizerRouter from "./optimizer.js";
import scannerRouter from "./scanner.js";
import correlationRouter from "./correlation.js";
import journalRouter from "./journal.js";
import validationRouter from "./validation.js";
import sentimentRouter from "./sentiment.js";
import exchangeRouter from "./exchange.js";
import engineRouter from "./engine.js";
import systemRouter from "./system.js";
import feesRouter from "./fees.js";
import mobileRouter from "./mobile.js";
import adaptersRouter from "./adapters.js";
import authRouter from "./auth.js";
import userSettingsRouter from "./userSettings.js";
import userNotificationsRouter from "./userNotifications.js";
import alpacaPaperRouter from "./alpacaPaper.js";
import userExchangesRouter from "./userExchanges.js";
import billingRouter from "./billing.js";
import adminAnalyticsRouter from "./adminAnalytics.js";
import platformOverviewRouter from "./platformOverview.js";
import operatorTelemetryRouter from "./operatorTelemetry.js";
import userConsentRouter from "./userConsent.js";
import pushTokensRouter from "./pushTokens.js";
import internalNotifyRouter from "./internalNotify.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(downloadRouter);
router.use(authRouter);
router.use(userSettingsRouter);
router.use(userNotificationsRouter);
router.use(userExchangesRouter);
router.use(billingRouter);
router.use(adminAnalyticsRouter);
router.use(platformOverviewRouter);
router.use(operatorTelemetryRouter);
router.use(userConsentRouter);
router.use(pushTokensRouter);
router.use(internalNotifyRouter);
router.use(signalsRouter);
router.use(tradesRouter);
router.use(portfolioRouter);
router.use(settingsRouter);
router.use(logsRouter);
router.use(backtestRouter);
router.use(candlesRouter);
router.use(marketDataRouter);
router.use(analysisRouter);
router.use(aiDecisionRouter);
router.use(riskManagementRouter);
router.use(simulationRouter);
router.use(optimizerRouter);
router.use(scannerRouter);
router.use(correlationRouter);
router.use(journalRouter);
router.use(validationRouter);
router.use(sentimentRouter);
router.use(exchangeRouter);
router.use(engineRouter);
router.use(systemRouter);
router.use(feesRouter);
router.use(mobileRouter);
router.use(adaptersRouter);
router.use(alpacaPaperRouter);

export default router;
