import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import downloadRouter from "./download.js";
import signalsRouter from "./signals.js";
import tradesRouter from "./trades.js";
import portfolioRouter from "./portfolio.js";
import settingsRouter from "./settings.js";
import logsRouter from "./logs.js";
import backtestRouter from "./backtest.js";
import candlesRouter from "./candles.js";
import marketDataRouter from "./marketData.js";
import analysisRouter from "./analysis.js";
import aiDecisionRouter from "./aiDecision.js";
import riskManagementRouter from "./riskManagement.js";
import simulationRouter from "./simulation.js";
import optimizerRouter from "./optimizer.js";
import scannerRouter from "./scanner.js";
import correlationRouter from "./correlation.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(downloadRouter);
router.use(signalsRouter);
router.use(tradesRouter);
router.use(portfolioRouter);
router.use(settingsRouter);
router.use(logsRouter);
router.use(backtestRouter);
router.use(candlesRouter);
router.use(marketDataRouter);
router.use(analysisRouter);
router.use(aiDecisionRouter);
router.use(riskManagementRouter);
router.use(simulationRouter);
router.use(optimizerRouter);
router.use(scannerRouter);
router.use(correlationRouter);

export default router;
