// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ait-commanddeck/CommandDeck.tsx": () => import("../components/mockups/ait-commanddeck/CommandDeck.tsx"),
  "./components/mockups/ait-pulsegrid/PulseGrid.tsx": () => import("../components/mockups/ait-pulsegrid/PulseGrid.tsx")
};
