const colors = {
  light: {
    text: "#1F2A1F",
    tint: "#5C7F5F",
    background: "#F6F8F3",
    foreground: "#1F2A1F",
    card: "#FFFFFF",
    cardForeground: "#1F2A1F",
    primary: "#5C7F5F",
    primaryForeground: "#FFFFFF",
    secondary: "#E4EDE4",
    secondaryForeground: "#2A4A2A",
    muted: "#EDF0E9",
    mutedForeground: "#6B7A6B",
    accent: "#8FAF8F",
    accentForeground: "#FFFFFF",
    destructive: "#D64E35",
    destructiveForeground: "#FFFFFF",
    border: "#DDE5DD",
    input: "#DDE5DD",
    success: "#5C7F5F",
    successForeground: "#FFFFFF",
    warning: "#C27B2A",
    warningForeground: "#FFFFFF",
  },

  dark: {
    text: "#E8F0EA",
    tint: "#7FBF8F",
    background: "#0F1412",
    foreground: "#E8F0EA",
    card: "#1A221D",
    cardForeground: "#E8F0EA",
    primary: "#7FBF8F",
    primaryForeground: "#0F1412",
    secondary: "#1E2E22",
    secondaryForeground: "#B8D4BC",
    muted: "#162019",
    mutedForeground: "#7A9A7E",
    accent: "#5C9F6F",
    accentForeground: "#FFFFFF",
    destructive: "#E06050",
    destructiveForeground: "#FFFFFF",
    border: "#2A3D2E",
    input: "#2A3D2E",
    success: "#7FBF8F",
    successForeground: "#0F1412",
    warning: "#D4943A",
    warningForeground: "#0F1412",
  },

  radius: 16,
};

export default colors;
