import {
  useQuery,
  useMutation,
  useQueryClient,
  type UseQueryResult,
} from "@tanstack/react-query";
import { authFetch, authFetchJson } from "@/lib/authFetch";

// ─────────────────────────────────────────────────────────────────────────────
// Typed react-query hooks for the Jarvis `/api/jarvis/*` surface. Every call
// routes through authFetch (locked transport invariant). No codegen — Jarvis
// owns its own contract types here.
// ─────────────────────────────────────────────────────────────────────────────

export interface JarvisBusiness {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisProject {
  id: string;
  businessId: string | null;
  name: string;
  description: string | null;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisAgent {
  id: string;
  name: string;
  role: string;
  description: string | null;
  status: string;
  agentType: string;
  capabilities: string[] | null;
  config: Record<string, unknown> | null;
  enabled: boolean;
  scheduleSeconds: number | null;
  priority: number;
  runtimeStatus: string;
  lastRunAt: string | null;
  lastRunStatus: string | null;
  lastError: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisWorkflow {
  id: string;
  name: string;
  description: string | null;
  trigger: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisAuditLog {
  id: string;
  userId: string;
  userEmail: string | null;
  action: string;
  entityType: string;
  entityId: string | null;
  metadata: Record<string, unknown> | null;
  createdAt: string;
}

export interface JarvisTask {
  id: string;
  title: string;
  description: string | null;
  status: string;
  priority: string;
  businessId: string | null;
  projectId: string | null;
  assigneeAgentId: string | null;
  dueAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisDecision {
  id: string;
  title: string;
  context: string | null;
  decision: string | null;
  rationale: string | null;
  status: string;
  businessId: string | null;
  decidedBy: string | null;
  decidedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisEscalation {
  id: string;
  title: string;
  description: string | null;
  severity: string;
  status: string;
  businessId: string | null;
  assigneeAgentId: string | null;
  resolvedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisApproval {
  id: string;
  title: string;
  description: string | null;
  status: string;
  requestedBy: string | null;
  decidedBy: string | null;
  decidedAt: string | null;
  businessId: string | null;
  policyId: string | null;
  subjectType: string | null;
  subjectId: string | null;
  autoGenerated: boolean;
  decisionReason: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisOperations {
  tasks: {
    total: number;
    byStatus: Record<string, number>;
    byPriority: Record<string, number>;
    overdue: number;
  };
  decisions: {
    total: number;
    byStatus: Record<string, number>;
    pending: number;
  };
  escalations: {
    total: number;
    byStatus: Record<string, number>;
    bySeverity: Record<string, number>;
    open: number;
    criticalOpen: number;
  };
  approvals: {
    total: number;
    byStatus: Record<string, number>;
    pending: number;
  };
  queues: {
    openTasks: JarvisTask[];
    openEscalations: JarvisEscalation[];
    pendingApprovals: JarvisApproval[];
    recentDecisions: JarvisDecision[];
  };
  generatedAt: number;
}

export interface JarvisDashboard {
  counts: {
    businesses: number;
    projects: number;
    agents: number;
    workflows: number;
  };
  recentActivity: JarvisAuditLog[];
  systemHealth: {
    apiStatus: string;
    databaseStatus: string;
    uptimeSeconds: number;
    activeAgents: number;
    activeWorkflows: number;
    timestamp: number;
  };
  generatedAt: number;
}

export type JarvisSettings = Record<string, unknown>;

const API = "/api/jarvis";

export const jarvisKeys = {
  dashboard: ["jarvis", "dashboard"] as const,
  businesses: ["jarvis", "businesses"] as const,
  projects: ["jarvis", "projects"] as const,
  agents: ["jarvis", "agents"] as const,
  workflows: ["jarvis", "workflows"] as const,
  auditLogs: ["jarvis", "audit-logs"] as const,
  settings: ["jarvis", "settings"] as const,
  tasks: ["jarvis", "tasks"] as const,
  decisions: ["jarvis", "decisions"] as const,
  escalations: ["jarvis", "escalations"] as const,
  approvals: ["jarvis", "approvals"] as const,
  operations: ["jarvis", "operations"] as const,
  categories: ["jarvis", "knowledge-categories"] as const,
  assets: ["jarvis", "knowledge-assets"] as const,
  memories: ["jarvis", "memories"] as const,
  relationships: ["jarvis", "knowledge-relationships"] as const,
  search: ["jarvis", "search"] as const,
  knowledgeGraph: ["jarvis", "knowledge-graph"] as const,
  memoryOverview: ["jarvis", "memory-overview"] as const,
  findings: ["jarvis", "findings"] as const,
  recommendations: ["jarvis", "recommendations"] as const,
  insights: ["jarvis", "insights"] as const,
  briefings: ["jarvis", "briefings"] as const,
  intelligenceOverview: ["jarvis", "intelligence-overview"] as const,
  runtimeStatus: ["jarvis", "runtime-status"] as const,
  runtimeOverview: ["jarvis", "runtime-overview"] as const,
  runtimeActivity: ["jarvis", "runtime-activity"] as const,
  agentRuns: ["jarvis", "agent-runs"] as const,
  agentMessages: ["jarvis", "agent-messages"] as const,
  workflowRuns: ["jarvis", "workflow-runs"] as const,
  delegations: ["jarvis", "delegations"] as const,
  routingRules: ["jarvis", "routing-rules"] as const,
  escalationChains: ["jarvis", "escalation-chains"] as const,
  commands: ["jarvis", "commands"] as const,
  commandRegistry: ["jarvis", "command-registry"] as const,
  orchestrationOverview: ["jarvis", "orchestration-overview"] as const,
  policies: ["jarvis", "policies"] as const,
  budgets: ["jarvis", "budgets"] as const,
  policyEvaluations: ["jarvis", "policy-evaluations"] as const,
  agentTrust: ["jarvis", "agent-trust"] as const,
  governanceOverview: ["jarvis", "governance-overview"] as const,
  cognitionEnabled: ["jarvis", "cognition-enabled"] as const,
  cognitionRuns: ["jarvis", "cognition-runs"] as const,
  cognitionRun: (id: string) => ["jarvis", "cognition-run", id] as const,
  cognitionOverview: ["jarvis", "cognition-overview"] as const,
  semanticStatus: ["jarvis", "semantic-status"] as const,
  voiceSettings: ["jarvis", "voice-settings"] as const,
  voiceSessions: ["jarvis", "voice-sessions"] as const,
  voiceTurns: (id: string) => ["jarvis", "voice-turns", id] as const,
};

// ── dashboard ────────────────────────────────────────────────────────────────

export function useJarvisDashboard(): UseQueryResult<JarvisDashboard> {
  return useQuery({
    queryKey: jarvisKeys.dashboard,
    queryFn: () => authFetchJson<JarvisDashboard>(`${API}/dashboard`),
    refetchInterval: 15000,
  });
}

// ── generic CRUD factory ─────────────────────────────────────────────────────

interface EntityConfig<T> {
  path: string;
  listKey: readonly unknown[];
  listField: string;
  itemField: string;
}

function makeListHook<T>(cfg: EntityConfig<T>) {
  return (): UseQueryResult<T[]> =>
    useQuery({
      queryKey: cfg.listKey,
      queryFn: async () => {
        const data = await authFetchJson<Record<string, T[]>>(`${API}/${cfg.path}`);
        return data[cfg.listField] ?? [];
      },
    });
}

function useInvalidateAll() {
  const qc = useQueryClient();
  return () => {
    qc.invalidateQueries({ queryKey: ["jarvis"] });
  };
}

// ── businesses ───────────────────────────────────────────────────────────────

export interface BusinessInput {
  name: string;
  description?: string | null;
  status?: string;
}

export const useBusinesses = makeListHook<JarvisBusiness>({
  path: "businesses",
  listKey: jarvisKeys.businesses,
  listField: "businesses",
  itemField: "business",
});

export function useCreateBusiness() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: BusinessInput) =>
      authFetchJson<{ business: JarvisBusiness }>(`${API}/businesses`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateBusiness() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: BusinessInput & { id: string }) =>
      authFetchJson<{ business: JarvisBusiness }>(`${API}/businesses/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteBusiness() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/businesses/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── projects ─────────────────────────────────────────────────────────────────

export interface ProjectInput {
  name: string;
  businessId?: string | null;
  description?: string | null;
  status?: string;
}

export const useProjects = makeListHook<JarvisProject>({
  path: "projects",
  listKey: jarvisKeys.projects,
  listField: "projects",
  itemField: "project",
});

export function useCreateProject() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: ProjectInput) =>
      authFetchJson<{ project: JarvisProject }>(`${API}/projects`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateProject() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: ProjectInput & { id: string }) =>
      authFetchJson<{ project: JarvisProject }>(`${API}/projects/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteProject() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/projects/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── agents ───────────────────────────────────────────────────────────────────

export interface AgentInput {
  name: string;
  role?: string | null;
  description?: string | null;
  status?: string;
  agentType?: string;
  capabilities?: string[] | null;
  config?: Record<string, unknown> | null;
  enabled?: boolean;
  scheduleSeconds?: number | null;
  priority?: number;
}

export const useAgents = makeListHook<JarvisAgent>({
  path: "agents",
  listKey: jarvisKeys.agents,
  listField: "agents",
  itemField: "agent",
});

export function useCreateAgent() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: AgentInput) =>
      authFetchJson<{ agent: JarvisAgent }>(`${API}/agents`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateAgent() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: AgentInput & { id: string }) =>
      authFetchJson<{ agent: JarvisAgent }>(`${API}/agents/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteAgent() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/agents/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── workflows ────────────────────────────────────────────────────────────────

export interface WorkflowInput {
  name: string;
  description?: string | null;
  trigger?: string | null;
  status?: string;
}

export const useWorkflows = makeListHook<JarvisWorkflow>({
  path: "workflows",
  listKey: jarvisKeys.workflows,
  listField: "workflows",
  itemField: "workflow",
});

export function useCreateWorkflow() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: WorkflowInput) =>
      authFetchJson<{ workflow: JarvisWorkflow }>(`${API}/workflows`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateWorkflow() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: WorkflowInput & { id: string }) =>
      authFetchJson<{ workflow: JarvisWorkflow }>(`${API}/workflows/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteWorkflow() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/workflows/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── audit logs ───────────────────────────────────────────────────────────────

export function useAuditLogs(limit = 100): UseQueryResult<JarvisAuditLog[]> {
  return useQuery({
    queryKey: [...jarvisKeys.auditLogs, limit],
    queryFn: async () => {
      const data = await authFetchJson<{ auditLogs: JarvisAuditLog[] }>(
        `${API}/audit-logs?limit=${limit}`,
      );
      return data.auditLogs ?? [];
    },
  });
}

// ── settings ─────────────────────────────────────────────────────────────────

export function useSettings(): UseQueryResult<JarvisSettings> {
  return useQuery({
    queryKey: jarvisKeys.settings,
    queryFn: async () => {
      const data = await authFetchJson<{ settings: JarvisSettings }>(`${API}/settings`);
      return data.settings ?? {};
    },
  });
}

export function useUpdateSettings() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (patch: JarvisSettings) =>
      authFetchJson<{ settings: JarvisSettings }>(`${API}/settings`, {
        method: "PUT",
        body: JSON.stringify(patch),
      }),
    onSuccess: invalidate,
  });
}

// ── tasks ────────────────────────────────────────────────────────────────────

export interface TaskInput {
  title: string;
  description?: string | null;
  status?: string;
  priority?: string;
  businessId?: string | null;
  projectId?: string | null;
  assigneeAgentId?: string | null;
  dueAt?: string | null;
}

export const useTasks = makeListHook<JarvisTask>({
  path: "tasks",
  listKey: jarvisKeys.tasks,
  listField: "tasks",
  itemField: "task",
});

export function useCreateTask() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: TaskInput) =>
      authFetchJson<{ task: JarvisTask }>(`${API}/tasks`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateTask() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: TaskInput & { id: string }) =>
      authFetchJson<{ task: JarvisTask }>(`${API}/tasks/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteTask() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/tasks/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── decisions ────────────────────────────────────────────────────────────────

export interface DecisionInput {
  title: string;
  context?: string | null;
  decision?: string | null;
  rationale?: string | null;
  status?: string;
  businessId?: string | null;
}

export const useDecisions = makeListHook<JarvisDecision>({
  path: "decisions",
  listKey: jarvisKeys.decisions,
  listField: "decisions",
  itemField: "decision",
});

export function useCreateDecision() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: DecisionInput) =>
      authFetchJson<{ decision: JarvisDecision }>(`${API}/decisions`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateDecision() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: DecisionInput & { id: string }) =>
      authFetchJson<{ decision: JarvisDecision }>(`${API}/decisions/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteDecision() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/decisions/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── escalations ──────────────────────────────────────────────────────────────

export interface EscalationInput {
  title: string;
  description?: string | null;
  severity?: string;
  status?: string;
  businessId?: string | null;
  assigneeAgentId?: string | null;
}

export const useEscalations = makeListHook<JarvisEscalation>({
  path: "escalations",
  listKey: jarvisKeys.escalations,
  listField: "escalations",
  itemField: "escalation",
});

export function useCreateEscalation() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: EscalationInput) =>
      authFetchJson<{ escalation: JarvisEscalation }>(`${API}/escalations`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateEscalation() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: EscalationInput & { id: string }) =>
      authFetchJson<{ escalation: JarvisEscalation }>(`${API}/escalations/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteEscalation() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/escalations/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── approvals ────────────────────────────────────────────────────────────────

export interface ApprovalInput {
  title: string;
  description?: string | null;
  status?: string;
  businessId?: string | null;
}

export const useApprovals = makeListHook<JarvisApproval>({
  path: "approvals",
  listKey: jarvisKeys.approvals,
  listField: "approvals",
  itemField: "approval",
});

export function useCreateApproval() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: ApprovalInput) =>
      authFetchJson<{ approval: JarvisApproval }>(`${API}/approvals`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateApproval() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: ApprovalInput & { id: string }) =>
      authFetchJson<{ approval: JarvisApproval }>(`${API}/approvals/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteApproval() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/approvals/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── operations dashboard ─────────────────────────────────────────────────────

export function useOperations(): UseQueryResult<JarvisOperations> {
  return useQuery({
    queryKey: jarvisKeys.operations,
    queryFn: () => authFetchJson<JarvisOperations>(`${API}/operations`),
    refetchInterval: 15000,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Sprint 3 — memory & knowledge layer
// ─────────────────────────────────────────────────────────────────────────────

export interface JarvisKnowledgeCategory {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  color: string | null;
  parentId: string | null;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisKnowledgeAsset {
  id: string;
  title: string;
  summary: string | null;
  content: string | null;
  assetType: string;
  sourceUrl: string | null;
  categoryId: string | null;
  businessId: string | null;
  tags: string[] | null;
  status: string;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisMemory {
  id: string;
  title: string;
  content: string | null;
  memoryType: string;
  importance: string;
  categoryId: string | null;
  businessId: string | null;
  sourceType: string | null;
  sourceId: string | null;
  pinned: boolean;
  tags: string[] | null;
  status: string;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisKnowledgeRelationship {
  id: string;
  sourceType: string;
  sourceId: string;
  targetType: string;
  targetId: string;
  relationType: string;
  note: string | null;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

// ── knowledge categories ─────────────────────────────────────────────────────

export interface CategoryInput {
  name: string;
  description?: string | null;
  color?: string | null;
  parentId?: string | null;
  status?: string;
}

export const useCategories = makeListHook<JarvisKnowledgeCategory>({
  path: "knowledge-categories",
  listKey: jarvisKeys.categories,
  listField: "categories",
  itemField: "category",
});

export function useCreateCategory() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: CategoryInput) =>
      authFetchJson<{ category: JarvisKnowledgeCategory }>(
        `${API}/knowledge-categories`,
        { method: "POST", body: JSON.stringify(input) },
      ),
    onSuccess: invalidate,
  });
}

export function useUpdateCategory() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: CategoryInput & { id: string }) =>
      authFetchJson<{ category: JarvisKnowledgeCategory }>(
        `${API}/knowledge-categories/${id}`,
        { method: "PUT", body: JSON.stringify(input) },
      ),
    onSuccess: invalidate,
  });
}

export function useDeleteCategory() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/knowledge-categories/${id}`, {
        method: "DELETE",
      }),
    onSuccess: invalidate,
  });
}

// ── knowledge assets ─────────────────────────────────────────────────────────

export interface AssetInput {
  title: string;
  summary?: string | null;
  content?: string | null;
  assetType?: string;
  sourceUrl?: string | null;
  categoryId?: string | null;
  businessId?: string | null;
  tags?: string[] | null;
  status?: string;
}

export const useAssets = makeListHook<JarvisKnowledgeAsset>({
  path: "knowledge-assets",
  listKey: jarvisKeys.assets,
  listField: "assets",
  itemField: "asset",
});

export function useCreateAsset() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: AssetInput) =>
      authFetchJson<{ asset: JarvisKnowledgeAsset }>(`${API}/knowledge-assets`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateAsset() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: AssetInput & { id: string }) =>
      authFetchJson<{ asset: JarvisKnowledgeAsset }>(`${API}/knowledge-assets/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteAsset() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/knowledge-assets/${id}`, {
        method: "DELETE",
      }),
    onSuccess: invalidate,
  });
}

// ── memories ─────────────────────────────────────────────────────────────────

export interface MemoryInput {
  title: string;
  content?: string | null;
  memoryType?: string;
  importance?: string;
  categoryId?: string | null;
  businessId?: string | null;
  sourceType?: string | null;
  sourceId?: string | null;
  pinned?: boolean;
  tags?: string[] | null;
  status?: string;
}

export const useMemories = makeListHook<JarvisMemory>({
  path: "memories",
  listKey: jarvisKeys.memories,
  listField: "memories",
  itemField: "memory",
});

export function useCreateMemory() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: MemoryInput) =>
      authFetchJson<{ memory: JarvisMemory }>(`${API}/memories`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateMemory() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: MemoryInput & { id: string }) =>
      authFetchJson<{ memory: JarvisMemory }>(`${API}/memories/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteMemory() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/memories/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── knowledge relationships ──────────────────────────────────────────────────

export type KnowledgeNodeType = "memory" | "asset" | "category" | "decision" | "task";

export interface RelationshipInput {
  sourceType: KnowledgeNodeType;
  sourceId: string;
  targetType: KnowledgeNodeType;
  targetId: string;
  relationType?: string;
  note?: string | null;
}

export const useRelationships = makeListHook<JarvisKnowledgeRelationship>({
  path: "knowledge-relationships",
  listKey: jarvisKeys.relationships,
  listField: "relationships",
  itemField: "relationship",
});

export function useCreateRelationship() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: RelationshipInput) =>
      authFetchJson<{ relationship: JarvisKnowledgeRelationship }>(
        `${API}/knowledge-relationships`,
        { method: "POST", body: JSON.stringify(input) },
      ),
    onSuccess: invalidate,
  });
}

export function useDeleteRelationship() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/knowledge-relationships/${id}`, {
        method: "DELETE",
      }),
    onSuccess: invalidate,
  });
}

// ── enterprise search ────────────────────────────────────────────────────────

export interface JarvisSearchResults {
  query: string;
  memories: JarvisMemory[];
  assets: JarvisKnowledgeAsset[];
  total: number;
}

export function useSearch(
  query: string,
  types?: KnowledgeNodeType[],
): UseQueryResult<JarvisSearchResults> {
  const q = query.trim();
  const typeParam = types && types.length > 0 ? `&types=${types.join(",")}` : "";
  return useQuery({
    queryKey: [...jarvisKeys.search, q, typeParam],
    queryFn: () =>
      authFetchJson<JarvisSearchResults>(
        `${API}/search?q=${encodeURIComponent(q)}${typeParam}`,
      ),
    enabled: q.length > 0,
  });
}

// ── knowledge graph (memory navigation) ──────────────────────────────────────

export interface JarvisGraphNode {
  id: string;
  type: KnowledgeNodeType;
  label: string;
  meta: Record<string, unknown>;
}

export interface JarvisGraphEdge {
  id: string;
  source: { type: string; id: string };
  target: { type: string; id: string };
  relationType: string;
  note: string | null;
}

export interface JarvisKnowledgeGraph {
  nodes: JarvisGraphNode[];
  edges: JarvisGraphEdge[];
  counts: {
    categories: number;
    assets: number;
    memories: number;
    relationships: number;
  };
  generatedAt: number;
}

export function useKnowledgeGraph(): UseQueryResult<JarvisKnowledgeGraph> {
  return useQuery({
    queryKey: jarvisKeys.knowledgeGraph,
    queryFn: () => authFetchJson<JarvisKnowledgeGraph>(`${API}/knowledge-graph`),
  });
}

// ── memory dashboard (overview) ──────────────────────────────────────────────

export interface JarvisMemoryOverview {
  counts: {
    memories: number;
    assets: number;
    categories: number;
    relationships: number;
    pinned: number;
  };
  memories: {
    byType: Record<string, number>;
    byImportance: Record<string, number>;
  };
  assets: {
    byType: Record<string, number>;
  };
  relationships: {
    byType: Record<string, number>;
  };
  pinnedMemories: JarvisMemory[];
  recentMemories: JarvisMemory[];
  recentAssets: JarvisKnowledgeAsset[];
  generatedAt: number;
}

export function useMemoryOverview(): UseQueryResult<JarvisMemoryOverview> {
  return useQuery({
    queryKey: jarvisKeys.memoryOverview,
    queryFn: () => authFetchJson<JarvisMemoryOverview>(`${API}/memory/overview`),
    refetchInterval: 15000,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Sprint 4 — executive intelligence layer
// ─────────────────────────────────────────────────────────────────────────────

export interface JarvisFinding {
  id: string;
  title: string;
  summary: string | null;
  detail: string | null;
  category: string;
  severity: string;
  confidence: number;
  source: string | null;
  businessId: string | null;
  projectId: string | null;
  tags: string[] | null;
  status: string;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisRecommendation {
  id: string;
  title: string;
  rationale: string | null;
  action: string | null;
  priority: string;
  impact: string;
  effort: string;
  findingId: string | null;
  businessId: string | null;
  tags: string[] | null;
  status: string;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisInsight {
  id: string;
  title: string;
  content: string | null;
  insightType: string;
  confidence: number;
  source: string | null;
  findingId: string | null;
  businessId: string | null;
  tags: string[] | null;
  status: string;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisBriefing {
  id: string;
  title: string;
  summary: string | null;
  content: string | null;
  period: string;
  audience: string;
  businessId: string | null;
  publishedAt: string | null;
  tags: string[] | null;
  status: string;
  sourceMode: string;
  cognitionRunId: string | null;
  citations: { type: string; id: string }[] | null;
  groundingScore: number | null;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

// ── findings ─────────────────────────────────────────────────────────────────

export interface FindingInput {
  title: string;
  summary?: string | null;
  detail?: string | null;
  category?: string;
  severity?: string;
  confidence?: number;
  source?: string | null;
  businessId?: string | null;
  projectId?: string | null;
  tags?: string[] | null;
  status?: string;
}

export const useFindings = makeListHook<JarvisFinding>({
  path: "findings",
  listKey: jarvisKeys.findings,
  listField: "findings",
  itemField: "finding",
});

export function useCreateFinding() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: FindingInput) =>
      authFetchJson<{ finding: JarvisFinding }>(`${API}/findings`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateFinding() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: FindingInput & { id: string }) =>
      authFetchJson<{ finding: JarvisFinding }>(`${API}/findings/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteFinding() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/findings/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── recommendations ──────────────────────────────────────────────────────────

export interface RecommendationInput {
  title: string;
  rationale?: string | null;
  action?: string | null;
  priority?: string;
  impact?: string;
  effort?: string;
  findingId?: string | null;
  businessId?: string | null;
  tags?: string[] | null;
  status?: string;
}

export const useRecommendations = makeListHook<JarvisRecommendation>({
  path: "recommendations",
  listKey: jarvisKeys.recommendations,
  listField: "recommendations",
  itemField: "recommendation",
});

export function useCreateRecommendation() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: RecommendationInput) =>
      authFetchJson<{ recommendation: JarvisRecommendation }>(
        `${API}/recommendations`,
        { method: "POST", body: JSON.stringify(input) },
      ),
    onSuccess: invalidate,
  });
}

export function useUpdateRecommendation() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: RecommendationInput & { id: string }) =>
      authFetchJson<{ recommendation: JarvisRecommendation }>(
        `${API}/recommendations/${id}`,
        { method: "PUT", body: JSON.stringify(input) },
      ),
    onSuccess: invalidate,
  });
}

export function useDeleteRecommendation() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/recommendations/${id}`, {
        method: "DELETE",
      }),
    onSuccess: invalidate,
  });
}

// ── insights ─────────────────────────────────────────────────────────────────

export interface InsightInput {
  title: string;
  content?: string | null;
  insightType?: string;
  confidence?: number;
  source?: string | null;
  findingId?: string | null;
  businessId?: string | null;
  tags?: string[] | null;
  status?: string;
}

export const useInsights = makeListHook<JarvisInsight>({
  path: "insights",
  listKey: jarvisKeys.insights,
  listField: "insights",
  itemField: "insight",
});

export function useCreateInsight() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: InsightInput) =>
      authFetchJson<{ insight: JarvisInsight }>(`${API}/insights`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateInsight() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: InsightInput & { id: string }) =>
      authFetchJson<{ insight: JarvisInsight }>(`${API}/insights/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteInsight() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/insights/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── briefings ────────────────────────────────────────────────────────────────

export interface BriefingInput {
  title: string;
  summary?: string | null;
  content?: string | null;
  period?: string;
  audience?: string;
  businessId?: string | null;
  tags?: string[] | null;
  status?: string;
}

export const useBriefings = makeListHook<JarvisBriefing>({
  path: "briefings",
  listKey: jarvisKeys.briefings,
  listField: "briefings",
  itemField: "briefing",
});

export function useCreateBriefing() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: BriefingInput) =>
      authFetchJson<{ briefing: JarvisBriefing }>(`${API}/briefings`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateBriefing() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: BriefingInput & { id: string }) =>
      authFetchJson<{ briefing: JarvisBriefing }>(`${API}/briefings/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteBriefing() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/briefings/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── Sprint 8: cognition (advisory-only LLM plane) ────────────────────────────

export type CognitionRunStatus =
  | "ok"
  | "degraded"
  | "error"
  | "budget_exceeded"
  | "disabled";

export interface JarvisCognitionRun {
  id: string;
  kind: string;
  agentId: string | null;
  agentType: string | null;
  model: string | null;
  params: Record<string, unknown> | null;
  promptHash: string | null;
  retrievedRefs: { type: string; id: string }[] | null;
  inputTokens: number;
  outputTokens: number;
  costMicros: number;
  latencyMs: number | null;
  status: CognitionRunStatus;
  groundingScore: number | null;
  rawOutput: string | null;
  parsedProposal: Record<string, unknown> | null;
  error: string | null;
  createdBy: string | null;
  createdAt: string;
}

export interface GenerateBriefingInput {
  query: string;
  instructions?: string | null;
  period?: string;
  audience?: string;
  businessId?: string | null;
  executiveUserId?: string | null;
}

export interface GenerateBriefingResult {
  ok: boolean;
  status: CognitionRunStatus;
  briefing: JarvisBriefing | null;
  runId: string | null;
  groundingScore: number | null;
  citations: { type: string; id: string }[];
  reason: string | null;
}

export interface PublishBriefingResult {
  decision: "allow" | "require_approval";
  reason: string;
  groundingScore: number | null;
  threshold: number;
  approvalId: string | null;
  briefing: JarvisBriefing | null;
}

export interface JarvisCognitionOverview {
  enabled: boolean;
  counts: {
    totalRuns: number;
    byStatus: Record<string, number>;
    byKind: Record<string, number>;
  };
  totalCostMicros: number;
  avgGroundingScore: number | null;
  budget: {
    name: string;
    consumedMicros: number;
    limitMicros: number;
    exceeded: boolean;
  } | null;
  recentRuns: JarvisCognitionRun[];
}

export function useCognitionEnabled(): UseQueryResult<boolean> {
  return useQuery({
    queryKey: jarvisKeys.cognitionEnabled,
    queryFn: async () => {
      const data = await authFetchJson<{ enabled: boolean }>(
        `${API}/cognition/enabled`,
      );
      return data.enabled;
    },
  });
}

export function useSetCognitionEnabled() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (enabled: boolean) =>
      authFetchJson<{ enabled: boolean }>(`${API}/cognition/enabled`, {
        method: "POST",
        body: JSON.stringify({ enabled }),
      }),
    onSuccess: invalidate,
  });
}

export function useGenerateBriefing() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: GenerateBriefingInput) =>
      authFetchJson<GenerateBriefingResult>(`${API}/briefings/generate`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function usePublishBriefing() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<PublishBriefingResult>(`${API}/briefings/${id}/publish`, {
        method: "POST",
      }),
    onSuccess: invalidate,
  });
}

export function useCognitionRuns(): UseQueryResult<JarvisCognitionRun[]> {
  return useQuery({
    queryKey: jarvisKeys.cognitionRuns,
    queryFn: async () => {
      const data = await authFetchJson<{ runs: JarvisCognitionRun[] }>(
        `${API}/cognition/runs`,
      );
      return data.runs ?? [];
    },
  });
}

export function useCognitionRun(
  id: string | null,
): UseQueryResult<JarvisCognitionRun> {
  return useQuery({
    queryKey: jarvisKeys.cognitionRun(id ?? ""),
    enabled: Boolean(id),
    queryFn: async () => {
      const data = await authFetchJson<{ run: JarvisCognitionRun }>(
        `${API}/cognition/runs/${id}`,
      );
      return data.run;
    },
  });
}

export function useCognitionOverview(): UseQueryResult<JarvisCognitionOverview> {
  return useQuery({
    queryKey: jarvisKeys.cognitionOverview,
    queryFn: () =>
      authFetchJson<JarvisCognitionOverview>(`${API}/cognition/overview`),
    refetchInterval: 15000,
  });
}

// ── Sprint 9: semantic retrieval (hybrid lexical + pgvector) ──────────────────

export interface JarvisSemanticStatus {
  enabled: boolean;
  indexerTickEnabled: boolean;
  model: string;
  hasApiKey: boolean;
  totals: { corpus: number; embedded: number };
  perType: Record<string, { corpus: number; embedded: number }>;
  lastRun: {
    status: string;
    createdAt: string;
    costMicros: number;
    error: string | null;
  } | null;
}

export interface JarvisBackfillResult {
  ok: boolean;
  scanned: number;
  upserted: number;
  skipped: number;
  empty: number;
  budgetExceeded: boolean;
  errored: boolean;
  error: string | null;
  perType: Record<string, { upserted: number; skipped: number }>;
}

export function useSemanticStatus(): UseQueryResult<JarvisSemanticStatus> {
  return useQuery({
    queryKey: jarvisKeys.semanticStatus,
    queryFn: () =>
      authFetchJson<JarvisSemanticStatus>(`${API}/cognition/semantic/status`),
    refetchInterval: 15000,
  });
}

export function useSetSemanticEnabled() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (enabled: boolean) =>
      authFetchJson<{ enabled: boolean }>(`${API}/cognition/semantic/enabled`, {
        method: "POST",
        body: JSON.stringify({ enabled }),
      }),
    onSuccess: invalidate,
  });
}

export function useSetIndexerTickEnabled() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (enabled: boolean) =>
      authFetchJson<{ enabled: boolean }>(
        `${API}/cognition/semantic/indexer-tick`,
        {
          method: "POST",
          body: JSON.stringify({ enabled }),
        },
      ),
    onSuccess: invalidate,
  });
}

export function useRunSemanticBackfill() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (limit?: number) =>
      authFetchJson<JarvisBackfillResult>(`${API}/cognition/semantic/backfill`, {
        method: "POST",
        body: JSON.stringify(limit != null ? { limit } : {}),
      }),
    onSuccess: invalidate,
  });
}

// ── intelligence dashboard (overview) ────────────────────────────────────────

export interface JarvisIntelligenceOverview {
  counts: {
    findings: number;
    recommendations: number;
    insights: number;
    briefings: number;
    openFindings: number;
    pendingRecommendations: number;
  };
  findings: {
    bySeverity: Record<string, number>;
    byStatus: Record<string, number>;
  };
  recommendations: {
    byPriority: Record<string, number>;
    byStatus: Record<string, number>;
  };
  insights: {
    byType: Record<string, number>;
  };
  briefings: {
    byStatus: Record<string, number>;
  };
  recentFindings: JarvisFinding[];
  recentRecommendations: JarvisRecommendation[];
  recentInsights: JarvisInsight[];
  recentBriefings: JarvisBriefing[];
  generatedAt: number;
}

export function useIntelligenceOverview(): UseQueryResult<JarvisIntelligenceOverview> {
  return useQuery({
    queryKey: jarvisKeys.intelligenceOverview,
    queryFn: () =>
      authFetchJson<JarvisIntelligenceOverview>(`${API}/intelligence/overview`),
    refetchInterval: 15000,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Sprint 5 — agent runtime & coordination
// ─────────────────────────────────────────────────────────────────────────────

export interface JarvisRuntimeStatus {
  running: boolean;
  startedAt: number | null;
  tickIntervalMs: number;
  lastTickAt: number | null;
  tickCount: number;
  inFlight: string[];
}

export interface JarvisAgentCatalogEntry {
  type: string;
  label: string;
  description: string;
  defaultCapabilities: string[];
  defaultScheduleSeconds: number;
  defaultPriority: number;
}

export interface JarvisAgentRun {
  id: string;
  agentId: string | null;
  agentName: string | null;
  agentType: string | null;
  trigger: string;
  status: string;
  summary: string | null;
  output: Record<string, unknown> | null;
  itemsProcessed: number;
  error: string | null;
  startedAt: string;
  finishedAt: string | null;
  durationMs: number | null;
}

export interface JarvisAgentMessage {
  id: string;
  fromAgentId: string | null;
  fromAgentName: string | null;
  toAgentId: string | null;
  toAgentName: string | null;
  runId: string | null;
  messageType: string;
  subject: string;
  body: string | null;
  payload: Record<string, unknown> | null;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisRuntimeOverview {
  runtime: JarvisRuntimeStatus;
  catalog: JarvisAgentCatalogEntry[];
  fleet: (JarvisAgent & { hasHandler: boolean })[];
  totals: {
    agents: number;
    enabled: number;
    runs: number;
    messages: number;
  };
  runsByStatus: { status: string; c: number }[];
  recentRuns: JarvisAgentRun[];
  recentMessages: JarvisAgentMessage[];
}

export interface JarvisRuntimeActivityEvent {
  id: string;
  ts: number;
  type: string;
  severity: string;
  agentId?: string | null;
  agentName?: string | null;
  agentType?: string | null;
  runId?: string | null;
  message: string;
  details?: Record<string, unknown>;
}

export interface JarvisRuntimeActivity {
  events: JarvisRuntimeActivityEvent[];
  cursor: number;
  status: JarvisRuntimeStatus;
}

export interface JarvisRunOutcome {
  ok: boolean;
  runId: string | null;
  summary?: string;
  error?: string;
}

export function useRuntimeStatus(): UseQueryResult<{
  status: JarvisRuntimeStatus;
  catalog: JarvisAgentCatalogEntry[];
}> {
  return useQuery({
    queryKey: jarvisKeys.runtimeStatus,
    queryFn: () =>
      authFetchJson<{ status: JarvisRuntimeStatus; catalog: JarvisAgentCatalogEntry[] }>(
        `${API}/runtime/status`,
      ),
    refetchInterval: 5000,
  });
}

export function useRuntimeOverview(): UseQueryResult<JarvisRuntimeOverview> {
  return useQuery({
    queryKey: jarvisKeys.runtimeOverview,
    queryFn: () => authFetchJson<JarvisRuntimeOverview>(`${API}/runtime/overview`),
    refetchInterval: 5000,
  });
}

export function useRuntimeActivity(limit = 200): UseQueryResult<JarvisRuntimeActivity> {
  return useQuery({
    queryKey: [...jarvisKeys.runtimeActivity, limit],
    queryFn: () =>
      authFetchJson<JarvisRuntimeActivity>(`${API}/runtime/activity?limit=${limit}`),
    refetchInterval: 5000,
  });
}

export function useAgentRuns(
  params: { agentId?: string; status?: string; limit?: number } = {},
): UseQueryResult<JarvisAgentRun[]> {
  const search = new URLSearchParams();
  if (params.agentId) search.set("agentId", params.agentId);
  if (params.status) search.set("status", params.status);
  if (params.limit) search.set("limit", String(params.limit));
  const qs = search.toString();
  return useQuery({
    queryKey: [...jarvisKeys.agentRuns, params],
    queryFn: async () => {
      const data = await authFetchJson<{ runs: JarvisAgentRun[] }>(
        `${API}/agent-runs${qs ? `?${qs}` : ""}`,
      );
      return data.runs ?? [];
    },
    refetchInterval: 5000,
  });
}

export function useAgentMessages(
  params: { status?: string; runId?: string; limit?: number } = {},
): UseQueryResult<JarvisAgentMessage[]> {
  const search = new URLSearchParams();
  if (params.status) search.set("status", params.status);
  if (params.runId) search.set("runId", params.runId);
  if (params.limit) search.set("limit", String(params.limit));
  const qs = search.toString();
  return useQuery({
    queryKey: [...jarvisKeys.agentMessages, params],
    queryFn: async () => {
      const data = await authFetchJson<{ messages: JarvisAgentMessage[] }>(
        `${API}/agent-messages${qs ? `?${qs}` : ""}`,
      );
      return data.messages ?? [];
    },
    refetchInterval: 5000,
  });
}

export function useStartRuntime() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: { tickIntervalMs?: number } = {}) =>
      authFetchJson<{ status: JarvisRuntimeStatus }>(`${API}/runtime/start`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useStopRuntime() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: () =>
      authFetchJson<{ status: JarvisRuntimeStatus }>(`${API}/runtime/stop`, {
        method: "POST",
      }),
    onSuccess: invalidate,
  });
}

export function useRunAgent() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ outcome: JarvisRunOutcome }>(`${API}/agents/${id}/run`, {
        method: "POST",
      }),
    onSuccess: invalidate,
  });
}

export function useSeedDefaultAgents() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: () =>
      authFetchJson<{
        created: { id: string; name: string; agentType: string }[];
        skipped: number;
      }>(`${API}/agents/seed-defaults`, { method: "POST" }),
    onSuccess: invalidate,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Sprint 6 — orchestration & coordination
// ─────────────────────────────────────────────────────────────────────────────

export interface JarvisWorkflowStepDef {
  key: string;
  agentType: string;
  action: string;
  dependsOn?: string[];
  input?: Record<string, unknown>;
  condition?: string;
}

export interface JarvisWorkflowDefinition {
  steps: JarvisWorkflowStepDef[];
}

export interface JarvisWorkflowFull extends JarvisWorkflow {
  definition: JarvisWorkflowDefinition | null;
  version: number;
  enabled: boolean;
}

export interface JarvisWorkflowRun {
  id: string;
  workflowId: string | null;
  workflowName: string | null;
  status: string;
  trigger: string;
  context: Record<string, unknown> | null;
  initiatedBy: string | null;
  stepsTotal: number;
  stepsCompleted: number;
  error: string | null;
  startedAt: string;
  finishedAt: string | null;
  durationMs: number | null;
  updatedAt: string;
  createdAt: string;
}

export interface JarvisWorkflowStepRow {
  id: string;
  workflowRunId: string | null;
  stepKey: string;
  sequence: number;
  agentId: string | null;
  agentName: string | null;
  agentType: string | null;
  action: string | null;
  dependsOn: string[] | null;
  status: string;
  input: Record<string, unknown> | null;
  output: Record<string, unknown> | null;
  error: string | null;
  startedAt: string | null;
  finishedAt: string | null;
  durationMs: number | null;
  createdAt: string;
}

export interface JarvisDelegation {
  id: string;
  fromAgentId: string | null;
  fromAgentName: string | null;
  toAgentId: string | null;
  toAgentName: string | null;
  taskId: string | null;
  workflowRunId: string | null;
  objective: string;
  action: string | null;
  input: Record<string, unknown> | null;
  status: string;
  priority: string;
  dueAt: string | null;
  result: Record<string, unknown> | null;
  error: string | null;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisRoutingRule {
  id: string;
  name: string;
  description: string | null;
  matchType: string;
  matchValue: string | null;
  targetAgentType: string | null;
  targetAgentId: string | null;
  chainId: string | null;
  fallbackAgentType: string | null;
  priority: number;
  enabled: boolean;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisRouteResult {
  targetAgentType: string;
  ruleId: string | null;
  chainId: string | null;
  reason: string;
  fallback: boolean;
}

export interface JarvisEscalationChainStep {
  id: string;
  chainId: string | null;
  level: number;
  sequence: number;
  agentType: string | null;
  agentId: string | null;
  slaSeconds: number;
  notifyRole: string | null;
  instruction: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisEscalationChain {
  id: string;
  name: string;
  description: string | null;
  enabled: boolean;
  status: string;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
  steps: JarvisEscalationChainStep[];
}

export interface JarvisCommand {
  id: string;
  commandText: string;
  verb: string | null;
  args: Record<string, unknown> | null;
  issuedBy: string | null;
  status: string;
  routedAgentType: string | null;
  routingRuleId: string | null;
  workflowRunId: string | null;
  delegationId: string | null;
  result: Record<string, unknown> | null;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisCommandVerbSpec {
  verb: string;
  description: string;
  kind: "direct" | "delegation" | "workflow";
  agentType?: string;
  action?: string;
  argsHint?: string;
}

export interface JarvisOrchestrationOverview {
  runtime: JarvisRuntimeStatus;
  totals: {
    workflows: number;
    enabledWorkflows: number;
    routingRules: number;
    escalationChains: number;
  };
  runsByStatus: { status: string; c: number }[];
  delegationsByStatus: { status: string; c: number }[];
  commandsByStatus: { status: string; c: number }[];
  recentRuns: JarvisWorkflowRun[];
  recentDelegations: JarvisDelegation[];
  recentCommands: JarvisCommand[];
  recentMessages: JarvisAgentMessage[];
  generatedAt: number;
}

// ── workflows (Sprint 6 full + execution) ────────────────────────────────────

export interface WorkflowFullInput {
  name: string;
  description?: string | null;
  trigger?: string | null;
  status?: string;
  definition?: JarvisWorkflowDefinition | null;
  enabled?: boolean;
}

export const useWorkflowsFull = makeListHook<JarvisWorkflowFull>({
  path: "workflows",
  listKey: jarvisKeys.workflows,
  listField: "workflows",
  itemField: "workflow",
});

export function useCreateWorkflowFull() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: WorkflowFullInput) =>
      authFetchJson<{ workflow: JarvisWorkflowFull }>(`${API}/workflows`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateWorkflowFull() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: Partial<WorkflowFullInput> & { id: string }) =>
      authFetchJson<{ workflow: JarvisWorkflowFull }>(`${API}/workflows/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useExecuteWorkflow() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({
      id,
      context,
    }: {
      id: string;
      context?: Record<string, unknown> | null;
    }) =>
      authFetchJson<{ runId: string }>(`${API}/workflows/${id}/execute`, {
        method: "POST",
        body: JSON.stringify({ context: context ?? null }),
      }),
    onSuccess: invalidate,
  });
}

// ── workflow runs ────────────────────────────────────────────────────────────

export function useWorkflowRuns(
  params: { workflowId?: string; status?: string; limit?: number } = {},
): UseQueryResult<JarvisWorkflowRun[]> {
  const search = new URLSearchParams();
  if (params.workflowId) search.set("workflowId", params.workflowId);
  if (params.status) search.set("status", params.status);
  if (params.limit) search.set("limit", String(params.limit));
  const qs = search.toString();
  return useQuery({
    queryKey: [...jarvisKeys.workflowRuns, params],
    queryFn: async () => {
      const data = await authFetchJson<{ workflowRuns: JarvisWorkflowRun[] }>(
        `${API}/workflow-runs${qs ? `?${qs}` : ""}`,
      );
      return data.workflowRuns ?? [];
    },
    refetchInterval: 5000,
  });
}

export function useWorkflowRun(
  id: string | null,
): UseQueryResult<{ workflowRun: JarvisWorkflowRun; steps: JarvisWorkflowStepRow[] }> {
  return useQuery({
    queryKey: [...jarvisKeys.workflowRuns, "detail", id],
    queryFn: () =>
      authFetchJson<{ workflowRun: JarvisWorkflowRun; steps: JarvisWorkflowStepRow[] }>(
        `${API}/workflow-runs/${id}`,
      ),
    enabled: !!id,
    refetchInterval: 5000,
  });
}

// ── delegations ──────────────────────────────────────────────────────────────

export interface DelegationInput {
  toAgentId?: string | null;
  toAgentType?: string | null;
  objective: string;
  action?: string | null;
  input?: Record<string, unknown> | null;
  priority?: "low" | "medium" | "high" | "critical";
  dueAt?: string | null;
}

export function useDelegations(
  params: { status?: string; limit?: number } = {},
): UseQueryResult<JarvisDelegation[]> {
  const search = new URLSearchParams();
  if (params.status) search.set("status", params.status);
  if (params.limit) search.set("limit", String(params.limit));
  const qs = search.toString();
  return useQuery({
    queryKey: [...jarvisKeys.delegations, params],
    queryFn: async () => {
      const data = await authFetchJson<{ delegations: JarvisDelegation[] }>(
        `${API}/delegations${qs ? `?${qs}` : ""}`,
      );
      return data.delegations ?? [];
    },
    refetchInterval: 5000,
  });
}

export function useCreateDelegation() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: DelegationInput) =>
      authFetchJson<{ delegation: JarvisDelegation }>(`${API}/delegations`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

// ── routing rules ────────────────────────────────────────────────────────────

export interface RoutingRuleInput {
  name: string;
  description?: string | null;
  matchType?: "any" | "command" | "category" | "capability" | "keyword";
  matchValue?: string | null;
  targetAgentType?: string | null;
  targetAgentId?: string | null;
  chainId?: string | null;
  fallbackAgentType?: string | null;
  priority?: number;
  enabled?: boolean;
}

export const useRoutingRules = makeListHook<JarvisRoutingRule>({
  path: "routing-rules",
  listKey: jarvisKeys.routingRules,
  listField: "routingRules",
  itemField: "routingRule",
});

export function useCreateRoutingRule() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: RoutingRuleInput) =>
      authFetchJson<{ routingRule: JarvisRoutingRule }>(`${API}/routing-rules`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateRoutingRule() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: Partial<RoutingRuleInput> & { id: string }) =>
      authFetchJson<{ routingRule: JarvisRoutingRule }>(`${API}/routing-rules/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteRoutingRule() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/routing-rules/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

export interface RouteTestInput {
  verb?: string | null;
  category?: string | null;
  capability?: string | null;
  text?: string | null;
  keywords?: string[];
}

export function useTestRoute() {
  return useMutation({
    mutationFn: (input: RouteTestInput) =>
      authFetchJson<{ result: JarvisRouteResult }>(`${API}/routing-rules/test`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
  });
}

// ── escalation chains ────────────────────────────────────────────────────────

export interface EscalationChainInput {
  name: string;
  description?: string | null;
  enabled?: boolean;
  status?: string;
}

export interface EscalationChainStepInput {
  level?: number;
  sequence?: number;
  agentType?: string | null;
  agentId?: string | null;
  slaSeconds?: number;
  notifyRole?: string | null;
  instruction?: string | null;
}

export const useEscalationChains = makeListHook<JarvisEscalationChain>({
  path: "escalation-chains",
  listKey: jarvisKeys.escalationChains,
  listField: "escalationChains",
  itemField: "escalationChain",
});

export function useCreateEscalationChain() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: EscalationChainInput) =>
      authFetchJson<{ escalationChain: JarvisEscalationChain }>(
        `${API}/escalation-chains`,
        { method: "POST", body: JSON.stringify(input) },
      ),
    onSuccess: invalidate,
  });
}

export function useUpdateEscalationChain() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: Partial<EscalationChainInput> & { id: string }) =>
      authFetchJson<{ escalationChain: JarvisEscalationChain }>(
        `${API}/escalation-chains/${id}`,
        { method: "PUT", body: JSON.stringify(input) },
      ),
    onSuccess: invalidate,
  });
}

export function useDeleteEscalationChain() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/escalation-chains/${id}`, {
        method: "DELETE",
      }),
    onSuccess: invalidate,
  });
}

export function useAddEscalationChainStep() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({
      chainId,
      ...input
    }: EscalationChainStepInput & { chainId: string }) =>
      authFetchJson<{ step: JarvisEscalationChainStep }>(
        `${API}/escalation-chains/${chainId}/steps`,
        { method: "POST", body: JSON.stringify(input) },
      ),
    onSuccess: invalidate,
  });
}

export function useDeleteEscalationChainStep() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ chainId, stepId }: { chainId: string; stepId: string }) =>
      authFetchJson<{ ok: boolean }>(
        `${API}/escalation-chains/${chainId}/steps/${stepId}`,
        { method: "DELETE" },
      ),
    onSuccess: invalidate,
  });
}

// ── executive commands ───────────────────────────────────────────────────────

export interface CommandInput {
  verb: string;
  commandText?: string | null;
  args?: Record<string, unknown> | null;
}

export function useCommands(
  params: { status?: string; limit?: number } = {},
): UseQueryResult<JarvisCommand[]> {
  const search = new URLSearchParams();
  if (params.status) search.set("status", params.status);
  if (params.limit) search.set("limit", String(params.limit));
  const qs = search.toString();
  return useQuery({
    queryKey: [...jarvisKeys.commands, params],
    queryFn: async () => {
      const data = await authFetchJson<{ commands: JarvisCommand[] }>(
        `${API}/commands${qs ? `?${qs}` : ""}`,
      );
      return data.commands ?? [];
    },
    refetchInterval: 5000,
  });
}

export function useCommandRegistry(): UseQueryResult<JarvisCommandVerbSpec[]> {
  return useQuery({
    queryKey: jarvisKeys.commandRegistry,
    queryFn: async () => {
      const data = await authFetchJson<{ registry: JarvisCommandVerbSpec[] }>(
        `${API}/commands/registry`,
      );
      return data.registry ?? [];
    },
  });
}

export function useIssueCommand() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: CommandInput) =>
      authFetchJson<{ command: JarvisCommand }>(`${API}/commands`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

// ── orchestration overview ───────────────────────────────────────────────────

export function useOrchestrationOverview(): UseQueryResult<JarvisOrchestrationOverview> {
  return useQuery({
    queryKey: jarvisKeys.orchestrationOverview,
    queryFn: () =>
      authFetchJson<JarvisOrchestrationOverview>(`${API}/orchestration/overview`),
    refetchInterval: 5000,
  });
}

// ── Sprint 7 — Governance, Policy & Trust ────────────────────────────────────

export interface JarvisPolicy {
  id: string;
  name: string;
  description: string | null;
  scopeType: string;
  scopeValue: string | null;
  effect: string;
  priority: number;
  enabled: boolean;
  conditions: {
    minTrustScore?: number;
    maxPerWindow?: number;
    windowSeconds?: number;
  } | null;
  requireApprovalRole: string;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisBudget {
  id: string;
  name: string;
  description: string | null;
  scopeType: string;
  scopeValue: string | null;
  limitCount: number;
  windowSeconds: number;
  consumed: number;
  windowStartedAt: string | null;
  enabled: boolean;
  createdBy: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisPolicyEvaluation {
  id: string;
  policyId: string | null;
  policyName: string | null;
  subjectType: string;
  subjectId: string | null;
  agentType: string | null;
  action: string | null;
  decision: string;
  reason: string | null;
  approvalId: string | null;
  trustScoreAtEval: number | null;
  budgetSnapshot: Record<string, unknown> | null;
  createdAt: string;
}

export interface JarvisAgentTrust {
  id: string;
  agentId: string | null;
  agentName: string | null;
  agentType: string | null;
  score: number;
  totalRuns: number;
  successfulRuns: number;
  failedRuns: number;
  deniedActions: number;
  approvedActions: number;
  windowStartedAt: string | null;
  lastComputedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisBudgetState {
  budgetId: string;
  name: string;
  consumed: number;
  limitCount: number;
  windowSeconds: number;
  exceeded: boolean;
}

export interface JarvisGovernanceResult {
  decision: "allow" | "deny" | "require_approval";
  policyId: string | null;
  policyName: string | null;
  reason: string;
  requireApprovalRole: string;
  trustScore: number | null;
  matchedBudget: JarvisBudgetState | null;
}

export interface JarvisGovernanceOverview {
  decisionBreakdown: { decision: string; c: number }[];
  pendingApprovals: JarvisApproval[];
  budgets: JarvisBudget[];
  trustLeaderboard: JarvisAgentTrust[];
  recentEvaluations: JarvisPolicyEvaluation[];
  generatedAt: number;
}

export interface PolicyInput {
  name: string;
  description?: string | null;
  scopeType?: "global" | "agent_type" | "action" | "verb" | "category" | "workflow";
  scopeValue?: string | null;
  effect?: "allow" | "deny" | "require_approval";
  priority?: number;
  enabled?: boolean;
  conditions?: {
    minTrustScore?: number;
    maxPerWindow?: number;
    windowSeconds?: number;
  } | null;
  requireApprovalRole?: string;
}

export interface BudgetInput {
  name: string;
  description?: string | null;
  scopeType?: "global" | "agent_type" | "action" | "verb";
  scopeValue?: string | null;
  limitCount?: number;
  windowSeconds?: number;
  enabled?: boolean;
}

export interface PolicyTestInput {
  subjectType: "command" | "delegation" | "workflow_step" | "escalation";
  agentType?: string | null;
  action?: string | null;
  verb?: string | null;
  category?: string | null;
  workflowName?: string | null;
}

export interface ApprovalDecisionInput {
  id: string;
  decision: "approve" | "reject";
  reason?: string | null;
}

// ── policies ─────────────────────────────────────────────────────────────────

export const usePolicies = makeListHook<JarvisPolicy>({
  path: "policies",
  listKey: jarvisKeys.policies,
  listField: "policies",
  itemField: "policy",
});

export function useCreatePolicy() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: PolicyInput) =>
      authFetchJson<{ policy: JarvisPolicy }>(`${API}/policies`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdatePolicy() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: Partial<PolicyInput> & { id: string }) =>
      authFetchJson<{ policy: JarvisPolicy }>(`${API}/policies/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeletePolicy() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/policies/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

export function useTestPolicy() {
  return useMutation({
    mutationFn: (input: PolicyTestInput) =>
      authFetchJson<{ result: JarvisGovernanceResult }>(`${API}/policies/test`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
  });
}

// ── budgets ──────────────────────────────────────────────────────────────────

export const useBudgets = makeListHook<JarvisBudget>({
  path: "budgets",
  listKey: jarvisKeys.budgets,
  listField: "budgets",
  itemField: "budget",
});

export function useCreateBudget() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (input: BudgetInput) =>
      authFetchJson<{ budget: JarvisBudget }>(`${API}/budgets`, {
        method: "POST",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useUpdateBudget() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: Partial<BudgetInput> & { id: string }) =>
      authFetchJson<{ budget: JarvisBudget }>(`${API}/budgets/${id}`, {
        method: "PUT",
        body: JSON.stringify(input),
      }),
    onSuccess: invalidate,
  });
}

export function useDeleteBudget() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: (id: string) =>
      authFetchJson<{ ok: boolean }>(`${API}/budgets/${id}`, { method: "DELETE" }),
    onSuccess: invalidate,
  });
}

// ── policy evaluations (read-only audit trail) ───────────────────────────────

export const usePolicyEvaluations = makeListHook<JarvisPolicyEvaluation>({
  path: "policy-evaluations",
  listKey: jarvisKeys.policyEvaluations,
  listField: "evaluations",
  itemField: "evaluation",
});

// ── agent trust (read-only scorecards) ───────────────────────────────────────

export const useAgentTrust = makeListHook<JarvisAgentTrust>({
  path: "agent-trust",
  listKey: jarvisKeys.agentTrust,
  listField: "trust",
  itemField: "trust",
});

// ── approval decision (resume / block a held subject) ────────────────────────

export function useApprovalDecision() {
  const invalidate = useInvalidateAll();
  return useMutation({
    mutationFn: ({ id, ...input }: ApprovalDecisionInput) =>
      authFetchJson<{ approval: JarvisApproval }>(
        `${API}/approvals/${id}/decision`,
        { method: "POST", body: JSON.stringify(input) },
      ),
    onSuccess: invalidate,
  });
}

// ── governance overview (dashboard read) ─────────────────────────────────────

export function useGovernanceOverview(): UseQueryResult<JarvisGovernanceOverview> {
  return useQuery({
    queryKey: jarvisKeys.governanceOverview,
    queryFn: () =>
      authFetchJson<JarvisGovernanceOverview>(`${API}/governance/overview`),
    refetchInterval: 5000,
  });
}

// ── voice (Voice v1 — executive voice interface) ─────────────────────────────
// Admin-gated. Transcripts-only (no audio is ever persisted). The turn upload
// sends a raw audio Blob through authFetch (locked transport invariant) — never
// bare fetch — and receives the readback as base64 in a JSON envelope.

export interface JarvisVoiceLink {
  type: string;
  id: string;
}

export interface JarvisVoiceSession {
  id: string;
  status: string;
  businessId: string | null;
  createdBy: string | null;
  userEmail: string | null;
  turnCount: number;
  startedAt: string;
  lastTurnAt: string | null;
  endedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JarvisVoiceTurn {
  id: string;
  sessionId: string | null;
  turnIndex: number;
  transcript: string | null;
  transcriptConfidence: number | null;
  intent: string | null;
  intentConfidence: number | null;
  capability: string | null;
  replyText: string | null;
  ttsOk: boolean;
  status: string;
  error: string | null;
  cognitionRunId: string | null;
  links: JarvisVoiceLink[] | null;
  costMicros: number;
  latencyMs: number | null;
  createdBy: string | null;
  createdAt: string;
}

export interface JarvisVoiceTurnResult {
  turnId: string | null;
  sessionId: string;
  intent: string;
  capability: string | null;
  transcript: string;
  transcriptConfidence: number | null;
  replyText: string;
  ttsOk: boolean;
  audioBase64: string | null;
  audioContentType: string | null;
  links: JarvisVoiceLink[];
  cognitionRunId: string | null;
  status: string;
  latencyMs: number;
}

export function useVoiceSettings(): UseQueryResult<{ enabled: boolean }> {
  return useQuery({
    queryKey: jarvisKeys.voiceSettings,
    queryFn: () => authFetchJson<{ enabled: boolean }>(`${API}/voice/settings`),
  });
}

export function useSetVoiceSettings() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (enabled: boolean) =>
      authFetchJson<{ enabled: boolean }>(`${API}/voice/settings`, {
        method: "POST",
        body: JSON.stringify({ enabled }),
      }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: jarvisKeys.voiceSettings });
    },
  });
}

export function useVoiceSessions(): UseQueryResult<JarvisVoiceSession[]> {
  return useQuery({
    queryKey: jarvisKeys.voiceSessions,
    queryFn: async () => {
      const data = await authFetchJson<{ sessions: JarvisVoiceSession[] }>(
        `${API}/voice/sessions`,
      );
      return data.sessions ?? [];
    },
  });
}

export function useSessionTurns(
  sessionId: string | null,
): UseQueryResult<{ session: JarvisVoiceSession; turns: JarvisVoiceTurn[] }> {
  return useQuery({
    queryKey: jarvisKeys.voiceTurns(sessionId ?? "none"),
    enabled: Boolean(sessionId),
    queryFn: () =>
      authFetchJson<{ session: JarvisVoiceSession; turns: JarvisVoiceTurn[] }>(
        `${API}/voice/sessions/${sessionId}/turns`,
      ),
  });
}

export function useStartVoiceSession() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (businessId?: string | null) =>
      authFetchJson<{ session: JarvisVoiceSession }>(`${API}/voice/sessions`, {
        method: "POST",
        body: JSON.stringify({ businessId: businessId ?? null }),
      }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: jarvisKeys.voiceSessions });
    },
  });
}

export function useEndVoiceSession() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (sessionId: string) =>
      authFetchJson<{ session: JarvisVoiceSession }>(
        `${API}/voice/sessions/${sessionId}/end`,
        { method: "POST" },
      ),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: jarvisKeys.voiceSessions });
    },
  });
}

export function usePurgeVoiceSession() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (sessionId: string) =>
      authFetchJson<{ purged: boolean; turnsDeleted: number }>(
        `${API}/voice/sessions/${sessionId}`,
        { method: "DELETE" },
      ),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: jarvisKeys.voiceSessions });
    },
  });
}

// Binary PTT upload. Sends the recorded audio Blob with its native mime type as
// the request body; the server runs STT → intent → capability → TTS and returns
// the readback envelope. Routed through authFetch (NOT bare fetch).
export function useVoiceTurn() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (args: {
      sessionId: string;
      audio: Blob;
    }): Promise<JarvisVoiceTurnResult> => {
      const mimeType = args.audio.type || "audio/webm";
      const qs = new URLSearchParams({
        sessionId: args.sessionId,
        mimeType,
      }).toString();
      const res = await authFetch(`${API}/voice/turn?${qs}`, {
        method: "POST",
        body: args.audio,
        headers: { "Content-Type": mimeType },
      });
      if (!res.ok) {
        let detail = "";
        try {
          detail = await res.clone().text();
        } catch {
          /* ignore */
        }
        throw new Error(`Voice turn failed (${res.status}): ${detail.slice(0, 200)}`);
      }
      return (await res.json()) as JarvisVoiceTurnResult;
    },
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({ queryKey: jarvisKeys.voiceTurns(vars.sessionId) });
      qc.invalidateQueries({ queryKey: jarvisKeys.voiceSessions });
    },
  });
}
